-- ###########################################################
-- SCHEMA DE BANCO DE DADOS - SISREG PRO
-- Data de Criação: 01/02/2026
-- ###########################################################

-- 1. TABELAS PRINCIPAIS
CREATE TABLE IF NOT EXISTS public.body_parts (
    id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sub_areas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    body_part_id TEXT REFERENCES public.body_parts(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.protocols (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    body_part_id TEXT REFERENCES public.body_parts(id),
    sub_area_id UUID REFERENCES public.sub_areas(id),
    problema TEXT NOT NULL,
    locais TEXT,
    exame TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    role TEXT DEFAULT 'user'
);

-- 2. TABELA DE AUDITORIA (LOGS)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_nome TEXT,
    item_id TEXT,
    operacao TEXT,
    usuario_email TEXT,
    dados_antigos JSONB,
    dados_novos JSONB,
    data_hora TIMESTAMPTZ DEFAULT now()
);

-- 3. SEGURANÇA (RLS)
ALTER TABLE public.body_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Exemplo de Políticas (Repetir para as outras conforme necessário)
CREATE POLICY "Leitura pública" ON public.protocols FOR SELECT USING (true);
CREATE POLICY "Admin total" ON public.protocols FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 4. FUNÇÕES E TRIGGERS (A LÓGICA DO BANCO)
CREATE OR REPLACE FUNCTION public.registrar_auditoria()
RETURNS TRIGGER AS $$
DECLARE v_user_email TEXT;
BEGIN
    v_user_email := (SELECT email FROM auth.users WHERE id = auth.uid());
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public.audit_logs (tabela_nome, item_id, operacao, usuario_email, dados_antigos)
        VALUES (TG_TABLE_NAME, OLD.id::text, TG_OP, v_user_email, to_jsonb(OLD));
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public.audit_logs (tabela_nome, item_id, operacao, usuario_email, dados_antigos, dados_novos)
        VALUES (TG_TABLE_NAME, NEW.id::text, TG_OP, v_user_email, to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSE -- INSERT
        INSERT INTO public.audit_logs (tabela_nome, item_id, operacao, usuario_email, dados_novos)
        VALUES (TG_TABLE_NAME, NEW.id::text, TG_OP, v_user_email, to_jsonb(NEW));
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER tr_auditoria_protocolos 
AFTER INSERT OR UPDATE OR DELETE ON public.protocols
FOR EACH ROW EXECUTE PROCEDURE registrar_auditoria();